version: '3.8'

services:
  api:
    build:
      context: .
      target: development
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - postgres
      - mailhog
    env_file:
      - .env.development
    networks:
      - app_network

  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - app_network

  adminer:
    image: adminer:latest
    ports:
      - '90:8080'
    depends_on:
      - postgres
    networks:
      - app_network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'
      - '91:8025'
    networks:
      - app_network

# volumes:
#   postgres_data:

networks:
  app_network:
    driver: bridge
